sudo: required
dist: trusty

services:
    - docker

language: go

go:
  -  1.9.x

branches:
  only:
    - master
    - f-acl

before_install:
    - sudo apt-get update
    - sudo apt-get install -y liblxc1 lxc-dev lxc
    - sudo apt-get install -y qemu
    - ./scripts/install_rkt.sh
    - ./scripts/install_consul.sh
    - ./scripts/install_vault.sh

install:
  - export TRAVIS_REPO_SLUG=hashicorp/nomad
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH git@github.com:hashicorp/nomad-enterprise.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - make bootstrap

script:
  - sudo -E "PATH=$PATH" make travis
