sudo: required
dist: trusty

services:
    - docker

language: go

go:
  -  1.9.x

git:
  depth: 300

branches:
  only:
    - master

before_install:
    - sudo apt-get update
    - sudo apt-get install -y liblxc1 lxc-dev lxc shellcheck
    - sudo apt-get install -y qemu
    - sudo bash ./scripts/travis-rkt.sh
    - sudo bash ./scripts/travis-consul.sh
    - sudo bash ./scripts/travis-vault.sh

install:
  - export TRAVIS_REPO_SLUG=hashicorp/nomad
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH git@github.com:hashicorp/nomad-enterprise.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf `git rev-parse $TRAVIS_COMMIT_RANGE | head -n1`
  - make bootstrap

script:
  - sudo -E "PATH=$PATH" make travis
